version: "3"

services:
  server:
    image: "http-over-uds-server:dev"
    volumes:
      - server-uds:/app/socket/
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
  client:
    image: "http-over-uds-client:dev"
    environment:
      - HOU_BENCHMARK_UDS=/app/socket/server.socks
      - HOU_BENCHMARK_CONCURRENCY=4,16,64,256,1024
      - HOU_BENCHMARK_DURATION=10s
    volumes:
      - server-uds:/app/socket/:ro

volumes:
  server-uds:
